/*
 Copyright (c) 2003-2021, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function u(a,c,b){c=l(c);var e,d;if(0===c.length)return a;e=XfEditor.tools.array.map(c,function(a){return h(a)},this);if(b.length!==e.length)return XfEditor.error("pastetools-failed-image-extraction",{rtf:c.length,html:b.length}),a;for(d=0;d<b.length;d++)if(0===b[d].indexOf("file://"))if(e[d]){var k=b[d].replace(/\\/g,"\\\\");a=a.replace(new RegExp("(\x3cimg [^\x3e]*src\x3d[\"']?)"+k),"$1"+e[d])}else XfEditor.error("pastetools-unsupported-image",{type:c[d].type,index:d});return a}function v(a,
c,b){var e=XfEditor.tools.array.unique(XfEditor.tools.array.filter(b,function(a){return a.match(/^blob:/i)}));b=XfEditor.tools.array.map(e,m);XfEditor.tools.promise.all(b).then(function(b){XfEditor.tools.array.forEach(b,function(b,c){if(b){var d=e[c],d=a.editable().find('img[src\x3d"'+d+'"]').toArray();XfEditor.tools.array.forEach(d,function(a){a.setAttribute("src",b);a.setAttribute("data-cke-saved-src",b)},this)}else XfEditor.error("pastetools-unsupported-image",{type:"blob",index:c})})});return c}
function l(a){function c(a){return"string"!==typeof a?-1:XfEditor.tools.array.indexOf(d,function(b){return b.id===a})}function b(a){var b=a.match(/\\blipuid (\w+)\}/);a=a.match(/\\bliptag(-?\d+)/);return b?b[1]:a?a[1]:null}var e=XfEditor.plugins.pastetools.filters.common.rtf,d=[];a=e.removeGroups(a,"(?:(?:header|footer)[lrf]?|nonshppict|shprslt)");a=e.getGroups(a,"pict");if(!a)return d;for(var k=0;k<a.length;k++){var g=a[k].content,h=b(g),n=r(g),f=c(h),p=-1!==f&&d[f].hex,l=p&&d[f].type===n,p=p&&d[f].type!==
n&&f===d.length-1,m=-1!==g.indexOf("\\defshp"),q=-1!==XfEditor.tools.array.indexOf(XfEditor.pasteFilters.image.supportedImageTypes,n);l?d.push(d[f]):p||m||(g={id:h,hex:q?e.extractGroupContent(g).replace(/\s/g,""):null,type:n},-1!==f?d.splice(f,1,g):d.push(g))}return d}function q(a){for(var c=/<img[^>]+src="([^"]+)[^>]+/g,b=[],e;e=c.exec(a);)b.push(e[1]);return b}function r(a){var c=XfEditor.tools.array.find(XfEditor.pasteFilters.image.recognizableImageTypes,function(b){return b.marker.test(a)});return c?
c.type:"unknown"}function h(a){var c=-1!==XfEditor.tools.array.indexOf(XfEditor.pasteFilters.image.supportedImageTypes,a.type),b=a.hex;if(!c)return null;"string"===typeof b&&(b=XfEditor.tools.convertHexStringToBytes(a.hex));return a.type?"data:"+a.type+";base64,"+XfEditor.tools.convertBytesToBase64(b):null}function m(a){return new XfEditor.tools.promise(function(c){XfEditor.ajax.load(a,function(a){a=new Uint8Array(a);var e=t(a);a=h({type:e,hex:a});c(a)},"arraybuffer")})}function t(a){a=a.subarray(0,
4);var c=XfEditor.tools.array.map(a,function(a){return a.toString(16)}).join("");return(a=XfEditor.tools.array.find(XfEditor.pasteFilters.image.recognizableImageSignatures,function(a){return 0===c.indexOf(a.signature)}))?a.type:null}XfEditor.pasteFilters.image=function(a,c,b){var e;if(c.activeFilter&&!c.activeFilter.check("img[src]"))return a;e=q(a);return 0===e.length?a:b?u(a,b,e):v(c,a,e)};XfEditor.pasteFilters.image.extractFromRtf=l;XfEditor.pasteFilters.image.extractTagsFromHtml=q;XfEditor.pasteFilters.image.getImageType=
r;XfEditor.pasteFilters.image.createSrcWithBase64=h;XfEditor.pasteFilters.image.convertBlobUrlToBase64=m;XfEditor.pasteFilters.image.getImageTypeFromSignature=t;XfEditor.pasteFilters.image.supportedImageTypes=["image/png","image/jpeg","image/gif"];XfEditor.pasteFilters.image.recognizableImageTypes=[{marker:/\\pngblip/,type:"image/png"},{marker:/\\jpegblip/,type:"image/jpeg"},{marker:/\\emfblip/,type:"image/emf"},{marker:/\\wmetafile\d/,type:"image/wmf"}];XfEditor.pasteFilters.image.recognizableImageSignatures=
[{signature:"ffd8ff",type:"image/jpeg"},{signature:"47494638",type:"image/gif"},{signature:"89504e47",type:"image/png"}]})();